version: '3.7'

services:
  line-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: db
    container_name: 'line-bot'
    restart: 'always' #on-failure
    #expose:
    #  - '4100'
    #ports:
    #  - '4100:4100'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - api_network
      # - postgres_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linebot.entrypoints=websecure"
      - "traefik.http.routers.linebot.rule=Host(`line-bot.dolfinminor.net`)"
      - "traefik.http.routers.linebot.service=line-bot"
      - "traefik.http.routers.linebot.tls=true"
      - "traefik.http.services.line-bot.loadbalancer.server.port=3000"
      - "traefik.docker.network=api_network"

networks:
  # postgres_network:
  #   external: true
  api_network:
    external: true